name: Docs Build (MyST-NB + RTD Mirror)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 2 * * *"

jobs:
  build-docs:
    name: Build and Test Documentation
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.13" ]
    defaults:
      run:
        shell: bash -l {0}
    env:
      CONDA_ENV_FILE: environment.yml
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      - name: Install micromamba environment
        uses: mamba-org/setup-micromamba@d7c9bd84e824b79d2af72a2d4196c7f4300d3476  # v3.0.0
        with:
          environment-name: radolan-guide
          environment-file: environment.yml
          cache-environment: true
          cache-environment-key: "${{runner.os}}-${{runner.arch}}-py${{env.PYTHON_VERSION}}-${{env.TODAY}}-${{hashFiles(env.CONDA_ENV_FILE)}}"
          create-args: >-
            python=${{matrix.python-version}}

      - name: pytest notebooks
        working-directory: notebooks
        run: |
          pytest -v -n auto

      - name: Build documentation with Sphinx
        run: |
          python -m sphinx -j auto -b html . _build/html -v

      - name: Upload HTML build (for PR inspection)
        if: ${{ success() }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
        with:
          name: docs-html
          path: _build/html
